// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 5.29.3
#include "pch.h"
#include "Protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr BuffData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : victims_{},
        _victims_cached_byte_size_{0},
        buffid_{::int64_t{0}},
        remaintime_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BuffData::BuffData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BuffDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuffDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuffDataDefaultTypeInternal() {}
  union {
    BuffData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuffDataDefaultTypeInternal _BuffData_default_instance_;

inline constexpr dummyMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : buffs_{},
        id_{::int64_t{0}},
        hp_{0},
        attack_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR dummyMessage::dummyMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct dummyMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR dummyMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~dummyMessageDefaultTypeInternal() {}
  union {
    dummyMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 dummyMessageDefaultTypeInternal _dummyMessage_default_instance_;
}  // namespace Protocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Protocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Protocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_Protocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffData, _impl_.buffid_),
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffData, _impl_.remaintime_),
        PROTOBUF_FIELD_OFFSET(::Protocol::BuffData, _impl_.victims_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::dummyMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::dummyMessage, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::Protocol::dummyMessage, _impl_.hp_),
        PROTOBUF_FIELD_OFFSET(::Protocol::dummyMessage, _impl_.attack_),
        PROTOBUF_FIELD_OFFSET(::Protocol::dummyMessage, _impl_.buffs_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Protocol::BuffData)},
        {11, -1, -1, sizeof(::Protocol::dummyMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Protocol::_BuffData_default_instance_._instance,
    &::Protocol::_dummyMessage_default_instance_._instance,
};
const char descriptor_table_protodef_Protocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016Protocol.proto\022\010Protocol\"\?\n\010BuffData\022\016"
    "\n\006buffid\030\001 \001(\003\022\022\n\nremainTime\030\002 \001(\002\022\017\n\007vi"
    "ctims\030\003 \003(\003\"Y\n\014dummyMessage\022\n\n\002id\030\001 \001(\003\022"
    "\n\n\002hp\030\002 \001(\005\022\016\n\006attack\030\003 \001(\005\022!\n\005buffs\030\004 \003"
    "(\0132\022.Protocol.BuffDatab\006proto3"
};
static ::absl::once_flag descriptor_table_Protocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false,
    false,
    190,
    descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_Protocol_2eproto::offsets,
    file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};
namespace Protocol {
// ===================================================================

class BuffData::_Internal {
 public:
};

BuffData::BuffData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.BuffData)
}
inline PROTOBUF_NDEBUG_INLINE BuffData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::BuffData& from_msg)
      : victims_{visibility, arena, from.victims_},
        _victims_cached_byte_size_{0},
        _cached_size_{0} {}

BuffData::BuffData(
    ::google::protobuf::Arena* arena,
    const BuffData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BuffData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, buffid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, buffid_),
           offsetof(Impl_, remaintime_) -
               offsetof(Impl_, buffid_) +
               sizeof(Impl_::remaintime_));

  // @@protoc_insertion_point(copy_constructor:Protocol.BuffData)
}
inline PROTOBUF_NDEBUG_INLINE BuffData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : victims_{visibility, arena},
        _victims_cached_byte_size_{0},
        _cached_size_{0} {}

inline void BuffData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, buffid_),
           0,
           offsetof(Impl_, remaintime_) -
               offsetof(Impl_, buffid_) +
               sizeof(Impl_::remaintime_));
}
BuffData::~BuffData() {
  // @@protoc_insertion_point(destructor:Protocol.BuffData)
  SharedDtor(*this);
}
inline void BuffData::SharedDtor(MessageLite& self) {
  BuffData& this_ = static_cast<BuffData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BuffData::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BuffData(arena);
}
constexpr auto BuffData::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BuffData, _impl_.victims_) +
          decltype(BuffData::_impl_.victims_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BuffData), alignof(BuffData), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BuffData::PlacementNew_,
                                 sizeof(BuffData),
                                 alignof(BuffData));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BuffData::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BuffData_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BuffData::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BuffData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BuffData::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BuffData>(), &BuffData::ByteSizeLong,
            &BuffData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BuffData, _impl_._cached_size_),
        false,
    },
    &BuffData::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BuffData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> BuffData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::BuffData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 buffid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(BuffData, _impl_.buffid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BuffData, _impl_.buffid_)}},
    // float remainTime = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(BuffData, _impl_.remaintime_)}},
    // repeated int64 victims = 3;
    {::_pbi::TcParser::FastV64P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(BuffData, _impl_.victims_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 buffid = 1;
    {PROTOBUF_FIELD_OFFSET(BuffData, _impl_.buffid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // float remainTime = 2;
    {PROTOBUF_FIELD_OFFSET(BuffData, _impl_.remaintime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // repeated int64 victims = 3;
    {PROTOBUF_FIELD_OFFSET(BuffData, _impl_.victims_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BuffData::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.BuffData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.victims_.Clear();
  ::memset(&_impl_.buffid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.remaintime_) -
      reinterpret_cast<char*>(&_impl_.buffid_)) + sizeof(_impl_.remaintime_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BuffData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BuffData& this_ = static_cast<const BuffData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BuffData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BuffData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.BuffData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 buffid = 1;
          if (this_._internal_buffid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_buffid(), target);
          }

          // float remainTime = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_remaintime()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_remaintime(), target);
          }

          // repeated int64 victims = 3;
          {
            int byte_size = this_._impl_._victims_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt64Packed(
                  3, this_._internal_victims(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.BuffData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BuffData::ByteSizeLong(const MessageLite& base) {
          const BuffData& this_ = static_cast<const BuffData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BuffData::ByteSizeLong() const {
          const BuffData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.BuffData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int64 victims = 3;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int64SizeWithPackedTagSize(
                      this_._internal_victims(), 1,
                      this_._impl_._victims_cached_byte_size_);
            }
          }
           {
            // int64 buffid = 1;
            if (this_._internal_buffid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_buffid());
            }
            // float remainTime = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_remaintime()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BuffData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BuffData*>(&to_msg);
  auto& from = static_cast<const BuffData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.BuffData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_victims()->MergeFrom(from._internal_victims());
  if (from._internal_buffid() != 0) {
    _this->_impl_.buffid_ = from._impl_.buffid_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_remaintime()) != 0) {
    _this->_impl_.remaintime_ = from._impl_.remaintime_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BuffData::CopyFrom(const BuffData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.BuffData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BuffData::InternalSwap(BuffData* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.victims_.InternalSwap(&other->_impl_.victims_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BuffData, _impl_.remaintime_)
      + sizeof(BuffData::_impl_.remaintime_)
      - PROTOBUF_FIELD_OFFSET(BuffData, _impl_.buffid_)>(
          reinterpret_cast<char*>(&_impl_.buffid_),
          reinterpret_cast<char*>(&other->_impl_.buffid_));
}

::google::protobuf::Metadata BuffData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class dummyMessage::_Internal {
 public:
};

dummyMessage::dummyMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.dummyMessage)
}
inline PROTOBUF_NDEBUG_INLINE dummyMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::dummyMessage& from_msg)
      : buffs_{visibility, arena, from.buffs_},
        _cached_size_{0} {}

dummyMessage::dummyMessage(
    ::google::protobuf::Arena* arena,
    const dummyMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  dummyMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, attack_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::attack_));

  // @@protoc_insertion_point(copy_constructor:Protocol.dummyMessage)
}
inline PROTOBUF_NDEBUG_INLINE dummyMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : buffs_{visibility, arena},
        _cached_size_{0} {}

inline void dummyMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, attack_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::attack_));
}
dummyMessage::~dummyMessage() {
  // @@protoc_insertion_point(destructor:Protocol.dummyMessage)
  SharedDtor(*this);
}
inline void dummyMessage::SharedDtor(MessageLite& self) {
  dummyMessage& this_ = static_cast<dummyMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* dummyMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) dummyMessage(arena);
}
constexpr auto dummyMessage::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.buffs_) +
          decltype(dummyMessage::_impl_.buffs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(dummyMessage), alignof(dummyMessage), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&dummyMessage::PlacementNew_,
                                 sizeof(dummyMessage),
                                 alignof(dummyMessage));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull dummyMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_dummyMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &dummyMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<dummyMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &dummyMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<dummyMessage>(), &dummyMessage::ByteSizeLong,
            &dummyMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_._cached_size_),
        false,
    },
    &dummyMessage::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* dummyMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2> dummyMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::dummyMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .Protocol.BuffData buffs = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.buffs_)}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(dummyMessage, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.id_)}},
    // int32 hp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(dummyMessage, _impl_.hp_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.hp_)}},
    // int32 attack = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(dummyMessage, _impl_.attack_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.attack_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int32 hp = 2;
    {PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.hp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 attack = 3;
    {PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.attack_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .Protocol.BuffData buffs = 4;
    {PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.buffs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::BuffData>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void dummyMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.dummyMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.buffs_.Clear();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.attack_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.attack_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* dummyMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const dummyMessage& this_ = static_cast<const dummyMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* dummyMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const dummyMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.dummyMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // int32 hp = 2;
          if (this_._internal_hp() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_hp(), target);
          }

          // int32 attack = 3;
          if (this_._internal_attack() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_attack(), target);
          }

          // repeated .Protocol.BuffData buffs = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_buffs_size());
               i < n; i++) {
            const auto& repfield = this_._internal_buffs().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.dummyMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t dummyMessage::ByteSizeLong(const MessageLite& base) {
          const dummyMessage& this_ = static_cast<const dummyMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t dummyMessage::ByteSizeLong() const {
          const dummyMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.dummyMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .Protocol.BuffData buffs = 4;
            {
              total_size += 1UL * this_._internal_buffs_size();
              for (const auto& msg : this_._internal_buffs()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // int64 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_id());
            }
            // int32 hp = 2;
            if (this_._internal_hp() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_hp());
            }
            // int32 attack = 3;
            if (this_._internal_attack() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_attack());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void dummyMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<dummyMessage*>(&to_msg);
  auto& from = static_cast<const dummyMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.dummyMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_buffs()->MergeFrom(
      from._internal_buffs());
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_hp() != 0) {
    _this->_impl_.hp_ = from._impl_.hp_;
  }
  if (from._internal_attack() != 0) {
    _this->_impl_.attack_ = from._impl_.attack_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void dummyMessage::CopyFrom(const dummyMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.dummyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void dummyMessage::InternalSwap(dummyMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.buffs_.InternalSwap(&other->_impl_.buffs_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.attack_)
      + sizeof(dummyMessage::_impl_.attack_)
      - PROTOBUF_FIELD_OFFSET(dummyMessage, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata dummyMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Protocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
